stages:
  - build
  - package

variables:
  BINARIES_DROP: "C:\\inetpub\\wwwroot"
  BINARIES_HREF: "http://bison.isat.xyz"

backend-build:
  stage: build
  script:
    - cd server
    - call ant distribute

frontend-build:
  stage: build
  script:
    - cd client
    - call npm install
    - call npm build
    - call npm run build

all-package:
  stage: package
  script:
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%