variables:
  BINARIES_DROP: "C:\\inetpub\\wwwroot"
  BINARIES_HREF: "http://bison.isat.xyz"

build:
  script:
    - cd server
    - call ant distribute
    - cd ..\client
    - call npm install
    - call npm run build
    - cd ..
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\server
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\css
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\scripts
    - copy server\bin\RestaurantServer.jar %BINARIES_DROP%\Bison-%CI_BUILD_ID%\server
    - copy client\*.html %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client
    - copy client\css\*.css %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\css
    - copy client\scripts\*.js %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\scripts
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin\locales
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin\css
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin\scripts
    - copy C:\Release\NWSJS\*.* %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin
    - copy C:\Release\NWSJS\locales\*.* %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin\locales
    - copy client\*.html %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin
    - copy client\*.json %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin
    - copy client\css\*.css %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin\css
    - copy client\scripts\*.js %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\bin\scripts
    - echo Binaries available at %BINARIES_HREF%/Bison-%CI_BUILD_ID%/