stages:
  - build
  - package

variables:
  BINARIES_DROP: "C:\\inetpub\\wwwroot"
  BINARIES_HREF: "http://bison.isat.xyz"

backend-build:
  stage: build
  script:
    - cd server
    - call ant distribute

frontend-build:
  stage: build
  script:
    - cd client
    - call npm install
    - call npm build
    - call npm run build

all-package:
  stage: package
  script:
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\server
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\css
    - mkdir %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\scripts
    - copy server/bin/RestaurantServer.jar %BINARIES_DROP%\Bison-%CI_BUILD_ID%\server
    - copy client\*.html %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client
    - copy client\css\*.css %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\css
    - copy client\scripts\*.js %BINARIES_DROP%\Bison-%CI_BUILD_ID%\client\scripts
    - echo Binaries available at %BINARIES_HREF%/%Bison-%CI_BUILD_ID%%/